### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loading' of undefined on LoginUser.js

### ISSUE THREAD

**Issue by colevels** [graphcool-examples/react-graphql#1]
![screen shot 2560-12-29 at 11 55 46](https://user-images.githubusercontent.com/24702575/34429785-633dda10-ec8f-11e7-8154-c6e09fe74b75.png)

it doesn't have this.props.data.

**Comment by doctorloaf** [comment]
Same here

**Comment by dansteren** [comment]
Had the same problem. Looks like LoginUser.js uses a named query meaning `this.props.data` should really be `this.props.loggedInUserQuery`. Just update lines 14 and 24 and you should be good.

I submitted a PR to fix this. See #5.
