### ISSUE TITLE
Getting started `git clone` wrong URI

### ISSUE THREAD

**Issue by alechp** [graphcool-examples/react-graphql#12]
File: https://github.com/graphcool-examples/react-graphql/blob/master/authentication-with-auth0-and-apollo/README.md

README says to do:

git clone https://github.com/graphcool-examples/react.git

Needs to be updated to:

git clone https://github.com/graphcool-examples/react-graphql.git

![screen shot 2017-05-25 at 8 36 54 am](https://cloud.githubusercontent.com/assets/3058939/26457531/573658c0-4125-11e7-8d5f-98778dc7cdd0.png)

**Comment by marktani** [comment]
Thanks for the heads up!
