### ISSUE TITLE
authentication-with-auth0-and-apollo live example not working

### ISSUE THREAD

**Issue by lkbr** [graphcool-examples/react-graphql#13]
After logging in with Auth0 on http://apollo-auth0.netlify.com/, I'm redirected to the homepage where the Login button and message still show. 

Console log:

```
Error: GraphQL error: The provided idToken is invalid. Please see https://auth0.com/docs/tokens/id_token for how to obtain a valid idToken
    at new t (main.9f08045f.js:11)
    at main.9f08045f.js:11
    at <anonymous>
```

**Comment by kbrandwijk** [comment]
This issue is closed, but the problem is still there?!

**Comment by fdidron** [comment]
Hi, I'm running into the same issue. @lkbr were you able to find a workaround ?

**Comment by fdidron** [comment]
Answering my own question since it might be useful for people encountering the same issue. Auth0 now returns JWT token with RS256 encryption instead of HS256 . So you would need to set encryption to HS256 in your auth0 Dashbord > Client > Advanced Settings.

**Comment by lkbr** [comment]
Not exactly, it worked when I cloned the example locally and used my own auth0 account, the example still fails.

**Comment by bleepsandblops** [comment]
Tried @fdidron's technique and it worked with the default app. For some reason it wouldn't let me change the encryption type in the one I created manually in auth0.
