### ISSUE TITLE
authentication-with-email-and-apollo has wrong schema

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool-examples/react-graphql#21]
This example is based on https://graphqlbin.com/insta-auth0.graphql, but the required field emailAddress in that schema breaks this project. Either the wrong schema is in the readme, or this example needs a different one.

**Comment by ngorman03** [comment]
Having the same issue

**Comment by tima101** [comment]
Initial Schema on User has both emailAddress and email.
App gives error, to fix - remove email attribute and keep emailAddress.

**Comment by chrisgchambers** [comment]
Correct schema found at https://graphqlbin.com/insta-email.graphql

Submitted PR to update README.md #34

**Comment by marktani** [comment]
Thanks so much @chrisgchambers!
