### ISSUE TITLE
Login/Signup currently fails - (Auth0 Example (with React & Apollo))

### ISSUE THREAD

**Issue by afishler** [graphcool-examples/react-graphql#29]
When running the code, after creating an account/client with Auth0, the result of signing up and completing the form is a redirect back to login.

The error is thrown in the catch part below of CreateUser, in the createUser function
this.props.createUser({ variables })
      .then((response) => {
          this.props.history.replace('/')
      }).catch((e) => {
        console.error(e)
        this.props.history.replace('/')
      })

with error:
CreateUser.js:80 Error: GraphQL error: The provided idToken is invalid. Please see https://auth0.com/docs/tokens/id_token for how to obtain a valid idToken
    at new ApolloError (apollo.umd.js:2075)
    at apollo.umd.js:2798
    at <anonymous>

**Comment by georgelam0306** [comment]
I'm also getting the same issue

**Comment by OGPoyraz** [comment]
Hey,
Did you tried to change Auth0 JWT encryption ? Go to your Auth0 Dashboard - Client - Advanced Settings. Then set JsonWebToken Signature Algorithm to HS256 inside OAuth tab.

**Comment by afishler** [comment]
HS256 worked. Thank you. However, don't recall this is indicated within the tutorial....would help to put it in clearly.

**Comment by andnilsson** [comment]
I´m getting the same invalid token error, but when i change to HS256 encryption I get this error response:
"Algorithm HS256 is not supported. (Expected algs: [RS256])"

**Comment by marktani** [comment]
Thanks everyone for chiming in! We're currently running a [beta for custom authentication](https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405?u=nilan), that allows you to build a RS256 compatible integration with Auth0. For further information, please join the discussion in the Forum: https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405?u=nilan.

**Comment by Joostvanderlaan** [comment]
Besides setting **JsonWebToken Signature Algorithm** to HS256, you also need to disable **OIDC Conformant** to make this example work. [See my pull request](https://github.com/graphcool-examples/react-graphql/pull/43)
