### ISSUE TITLE
Given URL is not whitelisted in Client OAuth Settings

### ISSUE THREAD

**Issue by gHashTag** [graphcool-examples/react-graphql#56]
I configure the file system authorization according to the steps in this [tutorial](https://www.graph.cool/docs/tutorials/auth/authentication-with-facebook-for-react-and-apollo-yi9jeuwohl) 
![2017-11-03 16 03 17](https://user-images.githubusercontent.com/6774813/32374886-8f6c48ac-c0b0-11e7-9aec-e7b0455bf34d.png)

and get an error:
`"Given URL is not whitelisted in Client OAuth Settings: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs."`

How do I fix this?

**Comment by marktani** [comment]
Are you running the app at `localhost:3000`?

**Comment by gHashTag** [comment]
@marktani  Yep
![authbug mov](https://user-images.githubusercontent.com/6774813/32377897-2b9bc7f8-c0ba-11e7-88c8-5e7c66bce8d7.gif)

**Comment by gHashTag** [comment]
Apologizing I did not correctly indicate FACEBOOK_APP_ID
