### ISSUE TITLE
authentication with facebook and apollo issues

### ISSUE THREAD

**Issue by miyi** [graphcool-examples/react-graphql#59]
I'm having trouble making it work. following the instructions i get this error response which is difficult to debug

```
Unhandled (in react-apollo) Error: GraphQL error: Cannot return null for non-nullable type (line 3, column 5):
    id
    ^
```

followed by this error

```
DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: function execution error: An unexpected error occured during authentication. could not be cloned.
```

**Comment by marktani** [comment]
What mutation results in this error?

You returned `null` for `id`, but `id` is required.

**Comment by miyi** [comment]
the tutorial appear unstable. I somehow managed to login once, but now a different error is showing

```
ApolloError.js:34 Uncaught (in promise) Error: GraphQL error: A function returned an unhandled error. Please check the logs for executionId 'us-west-2:simple:cj9tbr9zvb4iw0112w6t2ysub'
```

and on the error log

```
{"error":"Function returned invalid status code: 0. Raw body: empty.last"}
```

also just discovered the error log page does not expand the errors when you click on it, it just disappears

**Comment by miyi** [comment]
redid the project, fail to replicate error, works now
