### ISSUE TITLE
authentication-with-email-and-apollo not running

### ISSUE THREAD

**Issue by sallespro** [graphcool-examples/react-graphql#63]
`TypeError: Cannot read property 'loading' of undefined`

having issues with https://github.com/graphcool-examples/react-graphql/tree/master/authentication-with-email-and-apollo

i am not sure how `App` component passes down props to `CreateLogin`.
i am getting undefined out of `this.props.data.loading` at

```
  render () {
    if (this.props.data.loading) {
...
```

**Comment by heymartinadams** [comment]
@sallespro, these props get passed to `CreateLogin` via Apollo’s `compose` command:
Documentation: https://www.apollographql.com/docs/react/basics/setup.html#compose
https://github.com/graphcool-examples/react-graphql/blob/bfc4785d949d292bf18c4ccf7467cdca9b86e546/authentication-with-email-and-apollo/src/components/LoginUser.js#L78-L83

**Comment by sallespro** [comment]
hi @heymartinadams , tks for the heads up ! i havent made it yet.
i removed any reference to `this.props.data.loading`, but still not ok.

```index.js:2177 An error occured:  Error: GraphQL error: function execution error: An unexpected error occured.
    at new ApolloError (ApolloError.js:34)
    at Object.next (QueryManager.js:97)
    at SubscriptionObserver.next (zen-observable.js:154)
    at httpLink.js:127
    at <anonymous>```

**Comment by sallespro** [comment]
So, the server side issue was due to `graphcool-lib` update to ` "graphcool-lib": "^0.1.4",`

https://github.com/graphcool-examples/react-graphql/blob/master/authentication-with-email-and-apollo/server/package.json

but the `this.props.data.loading` is still a problem

**Comment by heymartinadams** [comment]
@sallespro: best to post debugging questions like this in the [Forum](https://www.graph.cool/forum/) as these may not be related to errors in the repository itself.

**Comment by sallespro** [comment]
the repository is graphcool-example, the error is in one of them and precisely in the intersection of the frameworks...but if you say the forum is best, i take your word for it.
